### ISSUE TITLE
PAUSE author being ignored when to look for specific version on MetaCPAN

### ISSUE THREAD

**Issue by miyagawa** [miyagawa/cpanminus#405]
```
➜  cpanminus git:(devel) ✗ perl -Ilib script/cpanm.PL --info App::cpanminus@1.7006 

---
filtered:
  query:
    nested:
      path: module
      query:
        custom_score:
          metacpan_script: score_version_numified
          query:
            constant_score:
              filter:
                and:
                  - term:
                      module.authorized: &1 !!perl/scalar:JSON::PP::Boolean 1
                  - term:
                      module.indexed: *1
                  - term:
                      module.name: App::cpanminus
                  - term:
                      module.version: 1.7006
      score_mode: max
...
  at /Users/miyagawa/dev/cpanminus/script/../lib/App/cpanminus/script.pm line 635
GMARLER/App-cpanminus-1.7006.tar.gz
```

http://api.metacpan.org/v0/release/_search?source=%7B%22filter%22%3A%7B%22term%22%3A%7B%22release.name%22%3A%22App-cpanminus-1.7006%22%7D%7D%2C%22fields%22%3A%5B%22download_url%22%2C%22stat%22%2C%22status%22%5D%7D

When to search for a module on MetaCPAN API, cpanm uses `module.authorized = true`, however when to lookup the matching release it uses the release key, such as `App-cpanminus-1.706`, which doesn't take into PAUSE author ID into account. If two authors upload a distribution with the same name, it is undefined which will be returned.
